[tool.poetry]
name = "yadirect-bigquery-connector"
version = "0.1.0"
description = ""
authors = ["tdcau-py <borisov.p.92@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
